var tree = {
  root: {
      photos:{
          folder1: ''
      },
      videos:{

      }
  }
};

var content = [
    {
        id: 1,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/fsry',
    },
    {
        id: 2,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/o0kv',
    },
    {
        id: 3,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/s6qj',
    },
    {
        id: 4,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/q40g',
    },
    {
        id: 5,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/9mo8',
    },
    {
        id: 6,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/l1nr',
    },
    {
        id: 7,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/z7hc',
    },
    {
        id: 8,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/vdis',
    },
    {
        id: 9,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/6t58',
    },
    {
        id: 10,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/yvs4',
    },
    {
        id: 11,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/nils',
    },
    {
        id: 12,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/w6n4',
    },
    {
        id: 13,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/km4w',
    },
    {
        id: 14,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/1r2f',
    },
    {
        id: 15,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/395d',
    },
    {
        id: 16,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/1arf',
    },
    {
        id: 17,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/r11n',
    },
    {
        id: 18,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/zrqu',
    },
    {
        id: 19,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/8tjc',
    },
    {
        id: 20,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/ksiu',
    },
    {
        id: 21,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/6rv6',
    },
    {
        id: 22,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/fqvr',
    },
    {
        id: 23,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/6yci',
    },
    {
        id: 24,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/g0p9',
    },
    {
        id: 25,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/71zr',
    },
    {
        id: 26,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/yyiq',
    },
    {
        id: 27,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/4lfl',
    },
    {
        id: 28,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/9hda',
    },
    {
        id: 29,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/r59f',
    },
    {
        id: 30,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/4g76',
    },
    {
        id: 31,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/enmm',
    },
    {
        id: 32,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/4sol',
    },
    {
        id: 33,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/j56o',
    },
    {
        id: 34,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/gyzb',
    },
    {
        id: 35,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/vmrb',
    },
    {
        id: 36,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/xs7g',
    },
    {
        id: 37,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/4dmk',
    },
    {
        id: 38,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/5b31',
    },
    {
        id: 39,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/klqr',
    },
    {
        id: 40,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/58c9',
    },
    {
        id: 41,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/kvfu',
    },
    {
        id: 42,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/prmr',
    },
    {
        id: 43,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/n3k7',
    },
    {
        id: 44,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/8wsm',
    },
    {
        id: 45,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/c3w7',
    },
    {
        id: 46,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/ny40',
    },
    {
        id: 47,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/a8a9',
    },
    {
        id: 48,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/h67t',
    },
    {
        id: 49,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/d3k4',
    },
    {
        id: 50,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/krps',
    },
    {
        id: 51,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/gs1r',
    },
    {
        id: 52,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/56z1',
    },
    {
        id: 53,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/veuk',
    },
    {
        id: 54,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/6mc0',
    },
    {
        id: 55,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/ihc6',
    },
    {
        id: 56,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/r993',
    },
    {
        id: 57,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/09j2',
    },
    {
        id: 58,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/28gj',
    },
    {
        id: 59,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/k4tz',
    },
    {
        id: 60,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/70nd',
    },
    {
        id: 61,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/h4ir',
    },
    {
        id: 62,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/238i',
    },
    {
        id: 63,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/8q77',
    },
    {
        id: 64,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/u2ej',
    },
    {
        id: 65,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/uvtb',
    },
    {
        id: 66,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/ljyi',
    },
    {
        id: 67,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/okzx',
    },
    {
        id: 68,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/vp06',
    },
    {
        id: 69,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/uwbc',
    },
    {
        id: 70,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/7qs4',
    },
    {
        id: 71,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/4n4y',
    },
    {
        id: 72,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/69ru',
    },
    {
        id: 73,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/tgti',
    },
    {
        id: 74,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/35q9',
    },
    {
        id: 75,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/qr4u',
    },
    {
        id: 76,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/fuqh',
    },
    {
        id: 77,
        title: '',
        type: 'streamable',
        url: 'https://streamable.com/uq50',
    },
];
