var tree = {
    root: {
        photos:{
            folder1: ''
        },
        videos:{

        }
    }
};

var content = [
    {
        id: 1,
        title: 'Первый Класс - ХУле.',
        type: 'streamable',
        url: 'https://streamable.com/fsry',
    },
    {
        id: 2,
        title: '360 флип плафон',
        type: 'streamable',
        url: 'https://streamable.com/o0kv',
    },
    {
        id: 3,
        title: 'Бабовску',
        type: 'streamable',
        url: 'https://streamable.com/s6qj',
    },
    {
        id: 4,
        title: 'Хэнговер',
        type: 'streamable',
        url: 'https://streamable.com/q40g',
    },
    {
        id: 5,
        title: 'Dexie13337Six Wallbang Airshots',
        type: 'streamable',
        url: 'https://streamable.com/9mo8',
    },
    {
        id: 6,
        title: 'Hardbass',
        type: 'streamable',
        url: 'https://streamable.com/l1nr',
    },
    {
        id: 7,
        title: 'LoganPack PhotoTrailer',
        type: 'streamable',
        url: 'https://streamable.com/z7hc',
    },
    {
        id: 8,
        title: 'LoganPack OfficoalPhoto Trailer',
        type: 'streamable',
        url: 'https://streamable.com/vdis',
    },
    {
        id: 9,
        title: 'Fristaylo Katapulta1337 Model',
        type: 'streamable',
        url: 'https://streamable.com/6t58',
    },
    {
        id: 10,
        title: 'LoganPack OfficialTrailer',
        type: 'streamable',
        url: 'https://streamable.com/yvs4',
    },
    {
        id: 11,
        title: 'LoganIntro',
        type: 'streamable',
        url: 'https://streamable.com/nils',
    },
    {
        id: 12,
        title: 'Outlast',
        type: 'streamable',
        url: 'https://streamable.com/w6n4',
    },
    {
        id: 13,
        title: 'ПолеЧуСед (Преза по Культурологии)',
        type: 'streamable',
        url: 'https://streamable.com/km4w',
    },
    {
        id: 14,
        title: 'Studio (Репетиция песни)',
        type: 'streamable',
        url: 'https://streamable.com/1r2f',
    },
    {
        id: 15,
        title: 'Таллин',
        type: 'streamable',
        url: 'https://streamable.com/395d',
    },
    {
        id: 16,
        title: 'Магмин Дом',
        type: 'streamable',
        url: 'https://streamable.com/1arf',
    },
    {
        id: 17,
        title: 'Адъская Колесница1',
        type: 'streamable',
        url: 'https://streamable.com/r11n',
    },
    {
        id: 18,
        title: 'Адъская Колесница2',
        type: 'streamable',
        url: 'https://streamable.com/zrqu',
    },
    {
        id: 19,
        title: 'Алкоголизм - это плохо',
        type: 'streamable',
        url: 'https://streamable.com/8tjc',
    },
    {
        id: 20,
        title: 'Аутласт1',
        type: 'streamable',
        url: 'https://streamable.com/ksiu',
    },
    {
        id: 21,
        title: 'Аутласт2',
        type: 'streamable',
        url: 'https://streamable.com/6rv6',
    },
    {
        id: 22,
        title: 'ВВВ',
        type: 'streamable',
        url: 'https://streamable.com/fqvr',
    },
    {
        id: 23,
        title: 'Водка со вкусом водки. Как я бухал с бабками.',
        type: 'streamable',
        url: 'https://streamable.com/6yci',
    },
    {
        id: 24,
        title: 'ВОЛЧАРА',
        type: 'streamable',
        url: 'https://streamable.com/g0p9',
    },
    {
        id: 25,
        title: 'ГРОУЛЪ',
        type: 'streamable',
        url: 'https://streamable.com/71zr',
    },
    {
        id: 26,
        title: 'ДасБут',
        type: 'streamable',
        url: 'https://streamable.com/yyiq',
    },
    {
        id: 27,
        title: 'Даша - шлюха это просто пиздец.',
        type: 'streamable',
        url: 'https://streamable.com/4lfl',
    },
    {
        id: 28,
        title: 'Динь Здаровиья',
        type: 'streamable',
        url: 'https://streamable.com/9hda',
    },
    {
        id: 29,
        title: 'Жидькие пельмешки',
        type: 'streamable',
        url: 'https://streamable.com/r59f',
    },
    {
        id: 30,
        title: 'Заседание НДБР',
        type: 'streamable',
        url: 'https://streamable.com/4g76',
    },
    {
        id: 31,
        title: 'Золотой дождь',
        type: 'streamable',
        url: 'https://streamable.com/enmm',
    },
    {
        id: 32,
        title: 'Ипполит Челендж',
        type: 'streamable',
        url: 'https://streamable.com/4sol',
    },
    {
        id: 33,
        title: 'ЙАРОСТЬНЫЙ ОЛIГ',
        type: 'streamable',
        url: 'https://streamable.com/j56o',
    },
    {
        id: 34,
        title: 'Как я бухал с бабками 2',
        type: 'streamable',
        url: 'https://streamable.com/gyzb',
    },
    {
        id: 35,
        title: 'Камасутра от БП',
        type: 'streamable',
        url: 'https://streamable.com/vmrb',
    },
    {
        id: 36,
        title: 'Крутые Яйца 2,5',
        type: 'streamable',
        url: 'https://streamable.com/xs7g',
    },
    {
        id: 37,
        title: 'Кулинарный хуй',
        type: 'streamable',
        url: 'https://streamable.com/4dmk',
    },
    {
        id: 38,
        title: 'Курлык Курлык',
        type: 'streamable',
        url: 'https://streamable.com/5b31',
    },
    {
        id: 39,
        title: 'Лоджия',
        type: 'streamable',
        url: 'https://streamable.com/klqr',
    },
    {
        id: 40,
        title: 'Магма в домике',
        type: 'streamable',
        url: 'https://streamable.com/58c9',
    },
    {
        id: 41,
        title: 'Магма Проспорил',
        type: 'streamable',
        url: 'https://streamable.com/kvfu',
    },
    {
        id: 42,
        title: 'Миниатюра - "факолет"',
        type: 'streamable',
        url: 'https://streamable.com/prmr',
    },
    {
        id: 43,
        title: 'Министр культуры НДБР',
        type: 'streamable',
        url: 'https://streamable.com/n3k7',
    },
    {
        id: 44,
        title: 'Молдавское Отборное',
        type: 'streamable',
        url: 'https://streamable.com/8wsm',
    },
    {
        id: 45,
        title: 'Мужчина - секс-машина',
        type: 'streamable',
        url: 'https://streamable.com/c3w7',
    },
    {
        id: 46,
        title: 'Мыльные пузыри',
        type: 'streamable',
        url: 'https://streamable.com/ny40',
    },
    {
        id: 47,
        title: 'Нирвана на даче',
        type: 'streamable',
        url: 'https://streamable.com/a8a9',
    },
    {
        id: 48,
        title: 'Новогодний тазик на Магме',
        type: 'streamable',
        url: 'https://streamable.com/h67t',
    },
    {
        id: 49,
        title: 'НУ ЧТОЖ ВЫ ЛЮДИ ДЕЛАЕТЕ НУ БУДЬТЕ ЛЮДЬМИ',
        type: 'streamable',
        url: 'https://streamable.com/d3k4',
    },
    {
        id: 50,
        title: 'Обзор на сварочный аппарат',
        type: 'streamable',
        url: 'https://streamable.com/krps',
    },
    {
        id: 51,
        title: 'Пей............ водку..........',
        type: 'streamable',
        url: 'https://streamable.com/gs1r',
    },
    {
        id: 52,
        title: 'Первоклассный Митол',
        type: 'streamable',
        url: 'https://streamable.com/56z1',
    },
    {
        id: 53,
        title: 'Панорама ЧГК',
        type: 'streamable',
        url: 'https://streamable.com/veuk',
    },
    {
        id: 54,
        title: 'Помидор ты что, думаешь самый умный?',
        type: 'streamable',
        url: 'https://streamable.com/6mc0',
    },
    {
        id: 55,
        title: 'Розовая лодка бомжа',
        type: 'streamable',
        url: 'https://streamable.com/ihc6',
    },
    {
        id: 56,
        title: 'Светлое беседка',
        type: 'streamable',
        url: 'https://streamable.com/r993',
    },
    {
        id: 57,
        title: 'Светлый хардбасс',
        type: 'streamable',
        url: 'https://streamable.com/09j2',
    },
    {
        id: 58,
        title: 'Слоник у Чувы',
        type: 'streamable',
        url: 'https://streamable.com/28gj',
    },
    {
        id: 59,
        title: 'Слэм на даче',
        type: 'streamable',
        url: 'https://streamable.com/k4tz',
    },
    {
        id: 60,
        title: 'Совещание НДБР (хуторное)',
        type: 'streamable',
        url: 'https://streamable.com/70nd',
    },
    {
        id: 61,
        title: 'Спортсмен епта...',
        type: 'streamable',
        url: 'https://streamable.com/h4ir',
    },
    {
        id: 62,
        title: 'СтыцаАТДорна',
        type: 'streamable',
        url: 'https://streamable.com/238i',
    },
    {
        id: 63,
        title: 'Ты куришь.... пиздюк',
        type: 'streamable',
        url: 'https://streamable.com/8q77',
    },
    {
        id: 64,
        title: 'Таборский Хардбасс',
        type: 'streamable',
        url: 'https://streamable.com/u2ej',
    },
    {
        id: 65,
        title: 'УУУУУУУУУУУУУУЛЕЙ',
        type: 'streamable',
        url: 'https://streamable.com/uvtb',
    },
    {
        id: 66,
        title: 'Фокусник - репер',
        type: 'streamable',
        url: 'https://streamable.com/ljyi',
    },
    {
        id: 67,
        title: 'Хардбасс в Науене',
        type: 'streamable',
        url: 'https://streamable.com/okzx',
    },
    {
        id: 68,
        title: 'Хардбасс в Фойе',
        type: 'streamable',
        url: 'https://streamable.com/vp06',
    },
    {
        id: 69,
        title: 'Харлем Магма',
        type: 'streamable',
        url: 'https://streamable.com/uwbc',
    },
    {
        id: 70,
        title: 'Хлiбнiй ДарЪ',
        type: 'streamable',
        url: 'https://streamable.com/7qs4',
    },
    {
        id: 71,
        title: 'Хуевая ручка на фоне Вии',
        type: 'streamable',
        url: 'https://streamable.com/4n4y',
    },
    {
        id: 72,
        title: 'Хуевая ручка',
        type: 'streamable',
        url: 'https://streamable.com/69ru',
    },
    {
        id: 73,
        title: 'Чейрмен',
        type: 'streamable',
        url: 'https://streamable.com/tgti',
    },
    {
        id: 74,
        title: 'Человек-противотанковый еж',
        type: 'streamable',
        url: 'https://streamable.com/35q9',
    },
    {
        id: 75,
        title: 'Чиллинг в науене',
        type: 'streamable',
        url: 'https://streamable.com/qr4u',
    },
    {
        id: 76,
        title: 'Ягер-Бомба',
        type: 'streamable',
        url: 'https://streamable.com/fuqh',
    },
    {
        id: 77,
        title: 'Ямка! Объехал!',
        type: 'streamable',
        url: 'https://streamable.com/uq50',
    },
];
